[project]
name = "sample-pokecon-package"
version = "0.1.0"
description = "package"
readme = "README.md"


[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"
